### ISSUE TITLE
Tribonacci

### ISSUE THREAD

**Issue by floppyzedolfin** [ablqk/adventofcode#13]
https://github.com/ablqk/adventofcode/blob/ae103194c9fe1c81d65464a2cfcfe4d4fbc30b8f/2020/dec10/part2.go#L39
The value for 5 is actually 13: https://math.stackexchange.com/a/3055328

And there's no reason it can't go beyond 5: this set of adapters is valid: `{1,2,3,4,5,6,7,8,9,10}`

**Comment by ablqk** [comment]
The value for 5 is fixed. There's not reason, but as it happens, it doesn't. Lucky me.
